mod j1;
mod j2;
mod j3;
mod j4;
mod j5;
mod j6;
mod j7;
mod j8;
mod j9;
mod j10;
mod j11;
mod j12;
mod j13;
mod j14;
mod j15;
mod j16;

fn main() {
    println!("J1 -----------------------------------------------------");
    println!("p1"); println!("{}", j1::p1());
    println!("p2"); println!("{}", j1::p2());
    println!();
    println!("J2 -----------------------------------------------------");
    println!("p1"); println!("{}", j2::p1());
    println!("p2"); println!("{}", j2::p2());
    println!();
    println!("J3 -----------------------------------------------------");
    println!("p1"); println!("{}", j3::p1());
    println!("p2"); println!("{}", j3::p2());
    println!();
    println!("J4 -----------------------------------------------------");
    println!("p1"); println!("{}", j4::p1());
    println!("p2"); println!("{}", j4::p2());
    println!();
    println!("J5 -----------------------------------------------------");
    println!("p1"); println!("{}", j5::p1());
    println!("p2"); println!("{}", j5::p2());
    println!();
    println!("J6 -----------------------------------------------------");
    println!("p1"); println!("{}", j6::p1());
    println!("p2"); println!("{}", j6::p2());
    println!();
    println!("J7 -----------------------------------------------------");
    println!("p1"); println!("{}", j7::p1());
    println!("p2"); println!("{}", j7::p2());
    println!();
    println!("J8 -----------------------------------------------------");
    println!("p1"); println!("{}", j8::p1());
    println!("p2"); println!("{}", j8::p2());
    println!();
    println!("J9 -----------------------------------------------------");
    println!("p1"); println!("{}", j9::p1());
    println!("p2"); println!("{}", j9::p2());
    println!();
    println!("J10 ----------------------------------------------------");
    println!("p1"); println!("{}", j10::p1());
    println!("p2"); println!("{}", j10::p2());
    println!();
    println!("J11 ----------------------------------------------------");
    println!("p1"); println!("{}", j11::p1());
    println!("p2"); println!("{}", j11::p2());
    println!();
    println!("J12 ----------------------------------------------------");
    println!("p1"); println!("{}", j12::p1());
    println!("p2"); println!("{}", j12::p2());
    println!();
    println!("J13 ----------------------------------------------------");
    println!("p1"); println!("{}", j13::p1());
    println!("p2"); println!("{}", j13::p2());
    println!("J14 ----------------------------------------------------");
    println!("p1"); println!("{}", j14::p1());
    println!("p2"); println!("{}", j14::p2());
    println!("J15 ----------------------------------------------------");
    println!("p1"); println!("{}", j15::p1());
    println!("p2"); println!("{}", j15::p2());
    println!("J16 ----------------------------------------------------");
    println!("p1"); println!("{}", j16::p1());
    println!("p2"); println!("{}", j16::p2());
}